# site settings
title: MUJER
subtitle: HOJALATA
email: soymujerhojalatagmail.com
description: Y llegó la hora de salir del closet y proclamarme artista medial 
baseurl: "/web-personal" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
# street_address: 1234 Somewhere Road
city: La falda de una de las Limas
# state: TN
# zip_code: 55555
country: Internets
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 10

# social settings
500px_url:
facebook_url:
github_url: https://github.com/mujerhojalata
# gitlab_url: https://gitlab.com/andrewbanchich
# googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://www.instagram.com/mujerhojalata/
linkedin_url: https://www.linkedin.com/in/jesenia-rodr%C3%ADguez-paredes-3077abba/
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/mujerhojalata
# build settings
markdown: kramdown

sass:
  style: compressed
